development:
  adapter: postgresql
  encoding: unicode
  database: easy_hackathon_development
  port: 5432

staging:
  adapter: postgresql
  encoding: unicode
  database: easy_hackathon_staging

test:
  adapter: postgresql
  encoding: unicode
  database: easy_hackathon_test
  port: 5432
