# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f325f32ac921bd589ff5fc840cfd4517a8a47baca00bda882956520a72506726dca1b4be7f652cedd3dca1452444f87334390c054996ab3b0a284467e162d7e

test:
  secret_key_base: 0336f65e06406940e77bb76c73f6720a799ffb4647c1516016fe5104eb7e9189660b1acb9299279e28766baaa1e1b5f72b39cbf19830ef381e7710bb547e1eca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
